#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export EDITOR=vim
export VISUAL=vim

# Aliases
alias be="bundle exec"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

export PATH="$PATH:$(yarn global bin)"

export PATH=$PATH:/usr/local/m-cli

# Git
alias g=git
alias grh="git reset --hard"
alias gf="git fetch"
alias gfm="git fetch && git checkout master && git reset --hard origin/master"

